#%RAML 1.0 DataType
displayName: Music Hub API
description: Defines the data type

type: object
properties: 
    id: string
    title: string
    artist: array
    thumbnail: string
    release_year: number
    duration: string
    likes: number
    category: array
    uri: string
    created: date